// Curated location list for the apply forms — Nigeria-first, with "Remote"
// and major global hubs for users targeting international roles.
// Order: Remote → all 36 Nigerian states + FCT (alpha) → top global cities (alpha).

export const LOCATIONS: string[] = [
  "Remote",
  "Hybrid",
  // Nigeria — states + FCT
  "Abia, Nigeria",
  "Adamawa, Nigeria",
  "Akwa Ibom, Nigeria",
  "Anambra, Nigeria",
  "Bauchi, Nigeria",
  "Bayelsa, Nigeria",
  "Benue, Nigeria",
  "Borno, Nigeria",
  "Cross River, Nigeria",
  "Delta, Nigeria",
  "Ebonyi, Nigeria",
  "Edo, Nigeria",
  "Ekiti, Nigeria",
  "Enugu, Nigeria",
  "FCT — Abuja, Nigeria",
  "Gombe, Nigeria",
  "Imo, Nigeria",
  "Jigawa, Nigeria",
  "Kaduna, Nigeria",
  "Kano, Nigeria",
  "Katsina, Nigeria",
  "Kebbi, Nigeria",
  "Kogi, Nigeria",
  "Kwara, Nigeria",
  "Lagos, Nigeria",
  "Nasarawa, Nigeria",
  "Niger, Nigeria",
  "Ogun, Nigeria",
  "Ondo, Nigeria",
  "Osun, Nigeria",
  "Oyo, Nigeria",
  "Plateau, Nigeria",
  "Rivers, Nigeria",
  "Sokoto, Nigeria",
  "Taraba, Nigeria",
  "Yobe, Nigeria",
  "Zamfara, Nigeria",
  // Major Nigerian cities (in case they want city-specific)
  "Ibadan, Nigeria",
  "Port Harcourt, Nigeria",
  "Benin City, Nigeria",
  "Aba, Nigeria",
  "Onitsha, Nigeria",
  "Warri, Nigeria",
  "Uyo, Nigeria",
  "Calabar, Nigeria",
  "Jos, Nigeria",
  "Ilorin, Nigeria",
  // Global hubs
  "Accra, Ghana",
  "Amsterdam, Netherlands",
  "Berlin, Germany",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "Dubai, UAE",
  "Dublin, Ireland",
  "Johannesburg, South Africa",
  "Kigali, Rwanda",
  "Lisbon, Portugal",
  "London, UK",
  "Manchester, UK",
  "Nairobi, Kenya",
  "New York, USA",
  "Paris, France",
  "San Francisco, USA",
  "Singapore",
  "Sydney, Australia",
  "Toronto, Canada",
];
