-- Remove fictional "Read the X guide" supporting tasks from existing user plans.
-- These were generated by an older plan version that pointed to /resources?tag=...
-- pages and guides that don't exist. The current generator no longer creates them.
DELETE FROM public.plan_tasks
WHERE slot > 0
  AND (
    title ILIKE 'Read the % guide'
    OR title ILIKE 'Read % guide'
    OR title ILIKE 'Review the % guide'
  )
  AND (cta_link ILIKE '/resources?tag=%' OR cta_link IS NULL);